# Sweep configuration for ablating batch size parameter
defaults:
  - config

# Override trainer config
trainer:
  num_tokens: 200000000

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      trainer.effective_batch_size: 1024,2048,4096,8192
      seed: 42,43,44,45,46
