# Sweep configuration for ablating SAE dimension parameter
defaults:
  - config

# Override trainer config
trainer:
  num_tokens: 200000000
  lr: 3e-4

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      sae.d_sae: 2560,5120,10240,20480
      seed: 42
